package cotesApp;


/**
* cotesApp/cotes.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Cotes.idl
* viernes 18 de octubre de 2019 11:15:49 AM BOT
*/

public interface cotes extends cotesOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface cotes
