package cotesApp;


/**
* cotesApp/cotesOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Cotes.idl
* viernes 18 de octubre de 2019 11:15:49 AM BOT
*/

public interface cotesOperations 
{
  String calcular (int idcliente);
  String pagar (String facturas);
  void shutdown ();
} // interface cotesOperations
