package cotesApp;


/**
* cotesApp/cotesHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Cotes.idl
* viernes 18 de octubre de 2019 11:15:49 AM BOT
*/

abstract public class cotesHelper
{
  private static String  _id = "IDL:cotesApp/cotes:1.0";

  public static void insert (org.omg.CORBA.Any a, cotesApp.cotes that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static cotesApp.cotes extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (cotesApp.cotesHelper.id (), "cotes");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static cotesApp.cotes read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_cotesStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, cotesApp.cotes value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static cotesApp.cotes narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof cotesApp.cotes)
      return (cotesApp.cotes)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      cotesApp._cotesStub stub = new cotesApp._cotesStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static cotesApp.cotes unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof cotesApp.cotes)
      return (cotesApp.cotes)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      cotesApp._cotesStub stub = new cotesApp._cotesStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
