package cotesApp;

/**
* cotesApp/cotesHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Cotes.idl
* viernes 18 de octubre de 2019 11:15:49 AM BOT
*/

public final class cotesHolder implements org.omg.CORBA.portable.Streamable
{
  public cotesApp.cotes value = null;

  public cotesHolder ()
  {
  }

  public cotesHolder (cotesApp.cotes initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = cotesApp.cotesHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    cotesApp.cotesHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return cotesApp.cotesHelper.type ();
  }

}
